// VueJS/vue-framework-intro/src/App.vue
<template>
  <div id="app">
    <div>
      <router-link to="/">Home</router-link>
      <router-link to="/blog">Blog</router-link>
      <router-link to="/account">Account</router-link>
    </div>
    <router-view></router-view>
    <!--app-user></app-user-->
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

// ReactJS/react-framework-intro/src/App.js
import './App.css';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';
import User from './components/User';
import Account from './components/Account';
import Blog from './components/Blog';

function App() {
  return (
    <Router>
      <div>
        <div>
          <Link to="/">Home</Link> ||
          <Link to="/account">Account</Link> ||
          <Link to="/blog">Blog</Link>
        </div>
        <hr />
        <Route exact path="/" component={User} />
        <Route path="/account" component={Account} />
        <Route path="/blog" component={Blog} />
      </div>
    </Router>
  );
}

export default App;
